# Generated by Django 4.2.4 on 2023-09-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('telephone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.TextField()),
                ('statu', models.CharField(choices=[('En cour', 'En cour'), ('Terminé', 'Terminé')], max_length=15)),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mtype', models.CharField(max_length=128)),
                ('num', models.IntegerField()),
                ('pre_comp', models.IntegerField(null=True)),
                ('after_comp', models.IntegerField(null=True)),
                ('statu', models.CharField(choices=[('En pause', 'En pause'), ('En utilisation', 'En utilisation')], default='stats', max_length=50)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence_machines', to='gestion.agence')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client'),
        ),
        migrations.AddField(
            model_name='agence',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.contrat'),
        ),
    ]
