# Generated by Django 4.2.4 on 2023-09-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='after_comp',
            new_name='after_compt',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='pre_comp',
            new_name='pre_compt',
        ),
    ]
