# Generated by Django 4.2.4 on 2023-09-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_after_comp_machine_after_compt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.client'),
        ),
    ]
