# Generated by Django 4.2.4 on 2023-09-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_contrat_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='cost',
        ),
        migrations.AlterField(
            model_name='contrat',
            name='description',
            field=models.TextField(default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
        ),
    ]
