# Generated by Django 4.2.4 on 2023-09-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commande',
        ),
    ]
